### ISSUE TITLE
Models and data

### ISSUE THREAD

**Issue by mloubout** [opesci/inversion#1]
What is the required format of this script for velocity models and data. How should the acquisition geometry be given?

**Comment by ggorman** [comment]
For the sake of a good abstraction I believe we need a generic class that provides a handle on the model and data. Within this we have to implement/instantiate the appropriate reader for each dataset (possibly pass it into the constructor). This way we can process different datasets without cluttering the top-level API.

Thus - for the sake of interoperability with your code I'm happy for you to tell me what your "native" format is. If you give me a 2D dataset along the lines we discussed yesterday then I'll implement a concrete implementation of a reader to illustrate this.

Related question - I have a seg y reader in but it currently does not have a good home as it's required in different places. Is this a good home for I/O in general as it is here that we also have to integrate with containers from other data frameworks (e.g. TensorFlow).
