### ISSUE TITLE
pep8 and re-engineering

### ISSUE THREAD

**Issue by ggorman** [opesci/inversion#10]
I have started hacking the ipython notebooks from Mathius into a solver class for inversion.

Immediate next tasks:
1. Get code to pass pep8 checks.
2. AcousticWave2D.py should run as a stand alone executable. Add as test.

**Comment by mloubout** [comment]
Added a bunch of function and filled Seismicdatareader.
Runs fine uptill line 385 (Forward is ok, Adjoint still have issues)

**Comment by mloubout** [comment]
@ggorman , @fmilthaler 
The full script is fixed and runs properlly, the only warning I get is 

AcousticWave2D.py:454: RuntimeWarning: invalid value encountered in double_scalars
  term1, term2, term1 - term2, term1 / term2
AcousticWave2D.py:506: RuntimeWarning: invalid value encountered in double_scalars
  term11, term21, term11 - term21, term11 / term21
C:\Users\mathias\Anaconda3\lib\site-packages\matplotlib\image.py:375: UserWarning: Images are not supported on non-linear axes.
  warnings.warn("Images are not supported on non-linear axes.")

which are only printing in terminal lines. Only thing left is to make it pretty and maybe a bit better organized I think.

**Comment by fmilthaler** [comment]
#11 Addresses most of the listed issues.
To close this issue, a test needs to be added. This can be done once travis is properly working.
