### ISSUE TITLE
SEG-Y shot data required for seg-y reader test case

### ISSUE THREAD

**Issue by ggorman** [opesci/inversion#14]
Need to generate a set (~10) of SEG-Y shot files to use as a test data. These need to be tiny - 10<sup>2</sup> (for 2D test) and 10<sup>3</sup> (for 3D). Set metadata in each case corresponding to the minimum set agreed with Charles. Let each trace be a simple sin curve with the magnitude corresponding to the shot id just so we can do basic sanity checks on the reader.

**Comment by mloubout** [comment]
@ggorman 
So the dataset already exist, I just need to put part of it. Where should I load it?

**Comment by ggorman** [comment]
I just noticed that there was an typo in my original message so please re-read for the size information. The dataset needs to be small.

It should be sufficiently small to just attach to one of your posts and I can take care of the integration.

**Comment by mloubout** [comment]
[DataSegy.zip](https://github.com/opesci/inversion/files/222616/DataSegy.zip)
Just a try, not the requested one, this is just 10 shots on the Marmousi model to see what size of file I can attach.

**Comment by ggorman** [comment]
It's not an unreasonable size and a standard test dataset. I'll run with this.
