### ISSUE TITLE
Details on optimization workflow

### ISSUE THREAD

**Issue by mloubout** [opesci/inversion#2]
First thing line 101 (curretly), the update direction is  -G so

model += alpha*gradient  has to be changed by 
model -= alpha*gradient 

and another tiny details, that usually helps reducing the number of iterations in the line search 

alpha = .5 * (min(1/v^2)) * 1/(max(abs(g)) is from my experience a ok guess

**Comment by ggorman** [comment]
Fixed in commit c8f2c22f6d37b87e3508d0285b0c8f1bb4458164
