### ISSUE TITLE
Add Marmousi subsurface model

### ISSUE THREAD

**Issue by ggorman** [opesci/inversion#21]
@mloubout - one for you. Can you give a URL for the Marmousi hard and smooth models - either in raw binary or RSF - that corresponds to the shots you previously provided?

**Comment by mloubout** [comment]
[Marmousi.zip](https://github.com/opesci/inversion/files/223958/Marmousi.zip)

**Comment by mloubout** [comment]
There is the binary and the header separated
the one starting with @ is the binary

**Comment by ggorman** [comment]
Does this exactly correspond to a standard copy of the Marmousi test case? If so can we instead have the URL?

**Comment by mloubout** [comment]
This is the one I used to generate the shots, it comes from our cluster and I am not sure where it came from as there is hundreds of version of this model online

**Comment by ggorman** [comment]
What smoothing filter do you use to create your "initial model"? i.e. assuming that it's a gaussian filter, what's the width of the filter.

**Comment by ggorman** [comment]
For reference: http://www.ahay.org/wiki/Guide_to_RSF_file_format

**Comment by mloubout** [comment]
This file only contains the true model. For an initial model, we usually convolutional smoothing, I know ow to use the operator but not what is inside of it. We can choose to do whatever we want as we know the true solution.

**Comment by mloubout** [comment]
> For reference: http://www.ahay.org/wiki/Guide_to_RSF_file_format

A little details, headers are not always separated, it is sometimes a unique file with the header at the beginning (like segy)

**Comment by ggorman** [comment]
Ok - we can create the smooth model for the test on the fly using:
http://stackoverflow.com/questions/29920114/how-to-gauss-filter-blur-a-floating-point-numpy-array
