### ISSUE TITLE
test_opesci_segy.py

### ISSUE THREAD

**Issue by mloubout** [opesci/inversion#25]
@ggorman 
    assert(len(files) == 10)
AssertionError

the two rsf files are breaking the test, we need to separate or change this file

**Comment by ggorman** [comment]
It looks like you are behind HEAD. git pull origin master.

**Comment by mloubout** [comment]
@ggorman 
My bad wasn't running it properly.
On the other hand, whatever I do I always get his error

    shots = ShotManager(comm, shotfiles)
  File "/Volumes/Users/mloubout/Dropbox/London/CodeGen/inversion/python/ShotManager.py", line 45, in __init__
    self.create_index(files)
  File "/Volumes/Users/mloubout/Dropbox/London/CodeGen/inversion/python/ShotManager.py", line 53, in create_index
    _files[i] = files[i]
TypeError: bytes or integer address expected instead of str instance

**Comment by mloubout** [comment]
@ggorman 
fixed
need to be replaced by 
_files[i] = bytes(files[i],encoding="utf-8")
