### ISSUE TITLE
Velocity model extension.

### ISSUE THREAD

**Issue by ggorman** [opesci/inversion#32]
@mloubout  said "The model we read is the true model, we need to extend it for the PML layer (add nbpml in each direction and pad it with the boundary value)"

@mloubout - is this the usual solution? A second option would be to assume that the nbpml on the boundary is sacrificed? Either way the boundary will not be accurate.

**Comment by mloubout** [comment]
It is absolutely necessary as the source and receiver are on top. sacrificing the points would remove the water layer and probably put the source inside the damping region.

**Comment by mloubout** [comment]
@ggorman 
There is actually a way to do without extending, but you need to play with indexes to axcees the boundary value from inside the PML

**Comment by ggorman** [comment]
Padding added.
