### ISSUE TITLE
Time interpolation. 

### ISSUE THREAD

**Issue by ggorman** [opesci/inversion#33]
@mloubout  "We need an operator that interpolates the time step axis (0:dt:(nt-1)*dt) to the shot axis (0:shotsample:length(shot))"

So - what I understand to be the right approach here is to perform a DFT of the trace, and then in Fourier space either trim or pad with zero's before doing a reverse transformation back into the time domain. The rational being that this doesn't add spurious frequencies. Can you confirm (and ideally provide a reference)?

**Comment by mloubout** [comment]
Polynomial interpolation is what I have always done as DFT is risky (can't guaranty you won't have artifact). The start and end times are the same so interpolation is fine

**Comment by ggorman** [comment]
Ok. What order polynomial do you typically use?

**Comment by ggorman** [comment]
Re-interpolation implemented and committed. Can you suggest a sensible test case for this?
