### ISSUE TITLE
MPI timeout

### ISSUE THREAD

**Issue by mloubout** [opesci/inversion#36]
Test project /Users/mloubout/Dropbox/London/CodeGen/inversion/build
    Start 1: SEG-Y
1/3 Test #1: SEG-Y ............................   Passed    3.02 sec
    Start 2: SHOT-RESAMPLE
2/3 Test #2: SHOT-RESAMPLE ....................   Passed    1.84 sec
    Start 3: MPI_FWI
3/3 Test #3: MPI_FWI ..........................***Timeout 1500.14 sec

**Comment by ggorman** [comment]
The test case is far too big for travis - takes too long to run. How about we subsample the model until it does run quickly enough?

**Comment by mloubout** [comment]
There is receiver positions all over the width of the model. but I can make a dummy smaller dataset and velocity model so that it tuns fast

**Comment by mloubout** [comment]
Or we can subsample the model and adjust the data we read

**Comment by ggorman** [comment]
I have added subsampling support for the model - however it throws up a bug in the propagator code. Can you take a look @mloubout ?

Traceback (most recent call last):
  File "python/fwi_mpi.py", line 105, in <module>
    worker.run()
  File "python/fwi_mpi.py", line 34, in run
    self.compute_gradient()
  File "python/fwi_mpi.py", line 27, in compute_gradient
    self.gradient = self.propagator.compute_gradient(self.model)
  File "/Users/ggorman/projects/opesci/inversion/python/AcousticWave2D.py", line 343, in compute_gradient
    [rec,u] = self.Forward(nt)
  File "/Users/ggorman/projects/opesci/inversion/python/AcousticWave2D.py", line 207, in Forward
    src, m[a, b], dt, h, damp)
IndexError: index 96 is out of bounds for axis 1 with size 96

**Comment by mloubout** [comment]
@ggorman 

FIxed, the shape was corresponding to the fully sampled velocity
