### ISSUE TITLE
Shot-Resample test failing (locally)

### ISSUE THREAD

**Issue by fmilthaler** [opesci/inversion#38]
`test_shot_reinterpolation.py` now spits out the following error:
```
2: Test timeout computed to be: 1500
2: Traceback (most recent call last):
2:   File "/data/fmilthaler/opesci/inversion2/tests/test_shot_reinterpolation.py", line 29, in <module>
2:     residule = shot.traces[:, :stop] - shot_ref.traces[:, :stop]
2: ValueError: operands could not be broadcast together with shapes (623,1001) (880,1001) 
2/3 Test #2: SHOT-RESAMPLE ....................***Failed    2.19 sec
```

This must have happened between abf3517d93042c2ef0aa354a4e4cd2d266d2f35d and 55f50b541d1fa6c8b7b1800d376d311146acd423

**Comment by mloubout** [comment]
Running tests...
Test project /home/ml1516/FWI-python/inversion/build
    Start 1: SEG-Y
1/3 Test #1: SEG-Y ............................   Passed    1.53 sec
    Start 2: SHOT-RESAMPLE
2/3 Test #2: SHOT-RESAMPLE ....................***Failed    0.94 sec
    Start 3: MPI_FWI

**Comment by mloubout** [comment]
@fmilthaler fixed
