### ISSUE TITLE
python implementation of isotropic acoustic inversion

### ISSUE THREAD

**Issue by ggorman** [opesci/inversion#6]
Implement Worker.calculate_partial_gradient by by cutting and pasting from @mloubout's  isotropic acoustic inversion notebook.

Inputs: model, shot_id
Output: Gradient

Depends upon #3.

**Comment by navjotk** [comment]
@ggorman If I understand correctly, @fmilthaler is working on this. Am I right?

**Comment by ggorman** [comment]
Yes - but keep an eye on the commits as its not a million miles away from working.

Gerard (mobile)

On 23 Mar 2016, at 18:55, Navjot Kukreja <notifications@github.com<mailto:notifications@github.com>> wrote:


@ggorman<https://github.com/ggorman> If I understand correctly, @fmilthaler<https://github.com/fmilthaler> is working on this. Am I right?

-
